### PR TITLE
Update to v0.0.13

### PR DESCRIPTION
**Pull request by aiivashchenko**
# Proposed Changes

-
-
-

Fixes #

### CODE REVIEW

**Comment by adracus** [comment]
@aiivashchenko what is the intent of this PR? Also, the history seems to have conflicts / originate from an earlier (rebased?) version

**Comment by aiivashchenko** [comment]
Hi @adracus. [capi-provider](https://github.com/onmetal/onmetal-api/tree/capi-provider) branch has been used to provide a convenient way to setup a test bench for `cluster-api` based on `kind`.

However, it is based on `onmetal-api@v0.0.9`.

Since `cluster-api-provider-onmetal` is using up-to-date version of `onmetal-api`, I'd like to update this branch correspondingly.

**Comment by afritzler** [comment]
You could just do a 
```
go get github.com/onmetal/onmetal-api@main
```
to get the latest version as a dependancy into your project.

**Comment by aiivashchenko** [comment]
Project itself imports `onmetal-api` properly. This branch contained just some modifications it order to simplify `kind` setup.

**Comment by adracus** [comment]
The latest `Makefile` is even better in that regard: You can simply run `kind deploy` to have a functional `onmetal-api` running on your local cluster.

**Comment by aiivashchenko** [comment]
I see. What is a proper `make` goal to load it into kind? `kind-install`?

**Comment by aiivashchenko** [comment]
Running it like like this gives me an error
```
~/onmetal-api$ make kind-install
docker build --target apiserver -t apiserver .
Sending build context to Docker daemon  61.41MB
Step 1/32 : FROM --platform=$BUILDPLATFORM golang:1.18 as builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
make: *** [Makefile:151: kind-build-apiserver] Error 1
```

`DOCKER_DEFAULT_PLATFORM` is set to `linux/amd64`

Do I need to make any extra prep steps?

**Comment by aiivashchenko** [comment]
I see, so `buildkit` should be enabled and there is a minimal version requirement for `kustomize`/`kubectl`.

v1.21 is a default one gardenlinux supplied with and it lacks `replacements` support.

Probably it is worth to be mentioned somewhere in docs.

But any other means, this is superior. Branch is no longer needed, and a pr as well.

**Comment by adracus** [comment]
The easiest target you're looking for is `kind-deploy` - this builds the images, loads them into the cluster and spins up the deployment.

If you're happy with that solution, please close the PR.

**Pull request closed without merging**
